kind: ConfigMap
apiVersion: v1
metadata:
  name: ovnkube-watcher-config
  namespace: kube-system
data:
  #cluster cidr
  k8s_cluster_cidr: "192.168.0.0/16"

---

kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: ovnkube-watcher
  namespace: kube-system
  labels:
    k8s-app: ovnkube-watcher
spec:
  selector:
    matchLabels:
      name: ovnkube-watcher
  template:
    metadata:
      labels:
        name: ovnkube-watcher
    spec:
      hostNetwork: true
      serviceAccountName: ovnkube-watcher-sa
      nodeSelector:
        kubernetes.io/role: "master"
      containers:
      - name: watcher
        image: ganboing/ovnkube:latest
        env:
        - name: OVN_K8S_CLUSTER_CIDR
          valueFrom:
            configMapKeyRef:
              name: ovnkube-watcher-config
              key: k8s_cluster_cidr
        - name: OVN_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ["/root/watcher.bash"]
        volumeMounts:
          - mountPath: /var/lib/kubelet
            name: kubelet
      volumes:
      - name: kubelet
        hostPath:
          path: /var/lib/kubelet
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ovnkube-watcher-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ovnkube-watcher-cr
subjects:
- kind: ServiceAccount
  name: ovnkube-watcher-sa
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ovnkube-watcher-cr
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - watch
    - list
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - nodes
    - services
    - endpoints
    - namespaces
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - extensions
    resources:
    - networkpolicies
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - networking.k8s.io
    resources:
    - networkpolicies
    verbs:
    - get
    - watch
    - list

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ovnkube-watcher-sa
  namespace: kube-system

---